# Generated by Django 3.2.24 on 2024-03-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0002_auto_20240302_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_img',
            field=models.ImageField(null=True, upload_to='courses_imgs/'),
        ),
        migrations.AddField(
            model_name='course',
            name='techs',
            field=models.TextField(null=True),
        ),
    ]
