# Generated by Django 3.2.24 on 2024-03-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0004_auto_20240303_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='video',
            new_name='vidio',
        ),
    ]
