# Generated by Django 3.2.24 on 2024-03-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0007_auto_20240305_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
    ]
